# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 10:12
from __future__ import unicode_literals

import cuisine_entre_amis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine_entre_amis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('text', 'Text'), ('tuto', 'Tutorial')], default='text', max_length=4, verbose_name='Type')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('publish_on', models.DateTimeField(blank=True, null=True, verbose_name='Publish on')),
            ],
            options={
                'ordering': ['-publish_on'],
            },
        ),
        migrations.CreateModel(
            name='PostPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nopic', 'No picture'), ('left', 'Picture on the left'), ('right', 'Picture on the right'), ('pic', 'One picture only')], default='left', max_length=5, verbose_name='Type')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=cuisine_entre_amis.models.get_path, verbose_name='Picture')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('ordernum', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cuisine_entre_amis.Post')),
            ],
            options={
                'ordering': ['ordernum'],
            },
        ),
        migrations.RemoveField(
            model_name='postlist',
            name='Author',
        ),
        migrations.DeleteModel(
            name='PostList',
        ),
    ]
