# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine_entre_amis', '0002_auto_20151229_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
