# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine_entre_amis', '0004_post_intro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuisine_entre_amis.Author'),
            preserve_default=False,
        ),
    ]
