# Generated by Django 2.1.1 on 2018-10-05 04:13

import cuisine_entre_amis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine_entre_amis', '0006_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro_pic',
            field=models.ImageField(blank=True, null=True, upload_to=cuisine_entre_amis.models.get_path),
        ),
    ]
