# Generated by Django 2.1.1 on 2018-10-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine_entre_amis', '0007_auto_20181005_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro_pic',
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
