# Generated by Django 2.1.1 on 2018-10-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine_entre_amis', '0009_author_bgimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_pic',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
